spring.application.name=Redbuild_AI_backend

spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/redbuildBD
spring.datasource.username=postgres
spring.datasource.password=2005


jwt.secret=Npzo4EZcN/abC50I2PWYinvoTh8aQ+4pT0BMKH/madA8AviccevWJ2gkivPFkevKN+7Nb1EQ2Tkt6kkctzgkFg==