# =========================================
# NOMBRE DE LA APLICACION
# =========================================
spring.application.name=Redbuild_AI_backend


# =========================================
# PUERTO
# =========================================
server.port=${PORT:8080}


# =========================================
# POSTGRESQL
# =========================================
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/redbuildBD}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:12345}

# =========================================
# HIBERNATE
# =========================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# =========================================
# SWAGGER
# =========================================
springdoc.openapi.info.title=ReBuild AI API
springdoc.openapi.info.description=Documentacion de la API de ReBuild AI protegida con Spring Security y JWT
springdoc.openapi.info.version=1.0


# =========================================
# JWT
# =========================================
jwt.secret=${JWT_SECRET:super-secret-key-redbuild-ai-change-me}